# Generated by Django 6.0 on 2025-12-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageModel',
        ),
        migrations.DeleteModel(
            name='TeacherMessageModel',
        ),
    ]
