# Generated by Django 6.0 on 2025-12-21 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmodel'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attendancesession'),
        ),
        migrations.AddField(
            model_name='section',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch'),
        ),
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teachermodel'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teachingassignment'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teachingassignment'),
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.year'),
        ),
        migrations.AddField(
            model_name='section',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.year'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='unique_student_session'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'section'), name='unique_teacher_subject_section'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('branch', 'year', 'name')},
        ),
    ]
