# Generated by Django 5.2.9 on 2026-02-04 13:52
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE api_attendancesession DROP COLUMN start_time;
                ALTER TABLE api_attendancesession ADD COLUMN start_time timestamp with time zone DEFAULT now() NOT NULL;
            """,
            reverse_sql="""
                ALTER TABLE api_attendancesession DROP COLUMN start_time;
                ALTER TABLE api_attendancesession ADD COLUMN start_time time without time zone DEFAULT now() NOT NULL;
            """,
            state_operations=[
                migrations.AlterField(
                    model_name='attendancesession',
                    name='start_time',
                    field=models.DateTimeField(auto_now_add=True),
                ),
            ]
        ),
    ]