# Generated by Django 5.2.9 on 2026-04-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_attendancesession_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='syllabus_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='syllabus_pdf',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/'),
        ),
    ]
