# Generated by Django 5.2.9 on 2026-04-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pendingscan'),
        ('app_messages', '0002_message_delete_messagemodel_and_more'),
        ('student', '0005_tasksubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='target_section',
        ),
        migrations.AddField(
            model_name='message',
            name='target_sections',
            field=models.ManyToManyField(blank=True, related_name='section_messages', to='api.section'),
        ),
        migrations.AddField(
            model_name='message',
            name='target_students',
            field=models.ManyToManyField(blank=True, related_name='student_messages', to='student.studentmodel'),
        ),
    ]
