# Generated by Django 5.2.9 on 2026-04-05 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_attendancesession_expires_at_and_more'),
        ('student', '0002_smarttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.section'),
        ),
    ]
