# Generated by Django 5.2.9 on 2026-04-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentmodel_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_pics/'),
        ),
    ]
