# Generated by Django 5.2.9 on 2026-08-29 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pendingscan'),
        ('student', '0005_tasksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='smarttask',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subject'),
        ),
        migrations.CreateModel(
            name='SectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_input', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('teaching_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_tasks', to='api.teachingassignment')),
            ],
        ),
        migrations.AddField(
            model_name='smarttask',
            name='section_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.sectiontask'),
        ),
        migrations.AddConstraint(
            model_name='sectiontask',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('teaching_assignment',), name='unique_active_section_task'),
        ),
    ]
